In [1]:
#Aluna: Mércia Regina da Silva
#Matricula: 201811250047
#Lista: Semana 08 e 09


import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as sla

In [2]:
def Resolve_Sistema(A,b):
    Ab = np.c_[A,b]
    n = len(A)
    
    for c in range(n-1):  
        for l in range(c+1,n):
            p = np.abs(Ab[c:,c]).argmax() + c
            Ab[[c,p]] = Ab[[p,c]]
            Ab[l] = Ab[l] - (Ab[l,c]/Ab[c,c])*Ab[c]
            
    C = Ab[:,:-1]
    d = Ab[:,-1]
    n1 = len(d)
    x = np.empty(n1)
    
    if(C[-1,-1] == 0):
        return "Matriz singular"
    
    x[-1] = d[-1]/C[-1,-1]

    for i in range(n1-2, -1, -1):
         x[i] = (d[i] - np.sum(C[i,i+1:]*x[i+1:]))/C[i,i]
    return x


In [3]:
def pivotamento(m):
    n = len(m)
    ID = [[float(i == j) for i in range(n)] for j in range(n)]
    for j in range(n):
        row = max(range(j, n), key=lambda i: abs(m[i][j]))
        if j != row:
            ID[j], ID[row] = ID[row], ID[j]
    return ID

In [14]:
def LU(A):
    n = len(A)
    L = [[0.0] * n for i in range(n)]
    U = [[0.0] * n for i in range(n)]
    
    P = pivotamento(A)
    A2 = np.array(P)@np.array(A)
    
    for j in range(n):
        L[j][j] = 1.0
        for i in range(j+1):
            s1 = sum(U[k][j] * L[i][k] for k in range(i))
            U[i][j] = A2[i][j] - s1
            
        for i in range(j, n):
            s2 = sum(U[k][j] * L[i][k] for k in range(j))
            L[i][j] = (A2[i][j] - s2) / U[j][j]
    return (np.array(L), np.array(U), np.array(P))


In [5]:
def sistema_linear_tri_sup(A, b):
    n = len(b)
    x = np.empty(n)
    
    x[-1] = b[-1]/A[-1, -1]
    
    for i in range(n-2, -1, -1):
        x[i] = (b[i] - np.sum(A[i,i+1:]*x[i+1:]))/A[i,i]
    return x

In [7]:
def dec_LU(L, U, P, b):
    Pb = P@b
    y = sistema_linear_tri_inf(L, Pb)
    x = sistema_linear_tri_sup(U, y)
    return x


In [8]:
def sistema_linear_tri_inf(A,b):
    n = len(b)
    x = np.empty(n)
    
    x[0] = b[0]/A[0, 0]
    
    for i in range(1,n):
        x[i] = (b[i] - np.sum(A[i,:i]*x[:i]))/A[i,i]
    return x

In [10]:
#Letra A
#x1 + x2 + x3 = 1
#4x1 + 4x2 + 2x3 = 2
#2x1 + x2 − x3 = 0
#COEFICIENTES DO SISTEMA - >

A = np.array([[1,1,1],[4,4,2],[2,1,-1]])
b = np.array([1,2,0])

print(Resolve_Sistema(A,b))
print(sla.solve(A,b))

Matriz singular
[ 1. -1.  1.]


In [16]:
A = np.array([[1,1,1],[4,4,2],[2,1,-1]])
b = np.array([1,2,0])

L, U, P = LU(A)
L_U, piv = sla.lu_factor(A)


print(dec_LU(L, U, P, b))

print(sla.lu_solve((L_U, piv), b))

[nan nan nan]
[ 1. -1.  1.]


/tmp/ipykernel_755/873686529.py:17: RuntimeWarning: invalid value encountered in double_scalars
  L[i][j] = (A2[i][j] - s2) / U[j][j]
/tmp/ipykernel_755/873686529.py:17: RuntimeWarning: divide by zero encountered in double_scalars
  L[i][j] = (A2[i][j] - s2) / U[j][j]


In [17]:
#Letra B
#7x1 − 7x2 + x3 = 1
#−3x1 + 3x2 + 2x3 = 2
#7x1 + 7x2 − 72x3 = 7
#coeficientes do sistema 

A = np.array([[7,-7,1],[-3,3,2],[7,7,-72]])
b = np.array([1,2,7])

print(Resolve_Sistema(A,b))
print(sla.solve(A,b))

[5.64285714 5.64285714 1.        ]
[5.64285714 5.64285714 1.        ]


In [18]:
A = np.array([[7,-7,1],[-3,3,2],[7,7,-72]])
b = np.array([1,2,7])

L, U, P = LU(A)
L_U, piv = sla.lu_factor(A)

print(dec_LU(L,U,P,b))
print(sla.lu_solve((L_U, piv), b))

[5.64285714 5.64285714 1.        ]
[5.64285714 5.64285714 1.        ]


In [19]:
#Letra C
#x1 + 2x2 + 3x3 + 4x4 = 20
#2x1 + 2x2 + 3x3 + 4x4 = 22
#3x1 + 3x2 + 3x3 + 4x4 = 22
#4x1 + 4x2 + 4x3 + 4x4 = 24
#coeficientes do sistema >

A = np.array([[1,2,3,4],[2,2,3,4],[3,3,3,4],[4,4,4,4]])
b = np.array([20,22,22,24])

print(Resolve_Sistema(A,b))
print(sla.solve(A,b))

[ 2. -2.  2.  4.]
[ 2. -2.  2.  4.]


In [20]:
A = np.array([[1,2,3,4],[2,2,3,4],[3,3,3,4],[4,4,4,4]])
b = np.array([20,22,22,24])

L, U, P = LU(A)
L_U, piv = sla.lu_factor(A)

print(dec_LU(L, U, P, b))
print(sla.lu_solve((L_U, piv), b))

[ 2. -2.  2.  4.]
[ 2. -2.  2.  4.]
