# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


#### 1. Import the numpy package under the name `np` (★☆☆)



In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆)



In [5]:
V = np.zeros(10)
print(V)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
V = np.zeros((10,10))
print("%d bytes" % (V.size * V.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

Exception: File `'`python.py'` not found.

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
V = np.zeros(10)
V[4] = 1
print(V)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
V = np.arange(10,50)
print(V)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
x = np.arange(12, 38)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
M = np.arange(9).reshape(3, 3)
print(M)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [15]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [17]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [18]:
V = np.random.random((3,3,3))
print(V)

[[[0.51941743 0.13283652 0.50066584]
  [0.41311423 0.41706522 0.57691884]
  [0.91293268 0.7112747  0.41610154]]

 [[0.85584615 0.89944483 0.83288771]
  [0.67112302 0.06454346 0.56643687]
  [0.19240499 0.47971876 0.9649158 ]]

 [[0.69828223 0.76819754 0.25007998]
  [0.70851347 0.43846551 0.88069152]
  [0.65741313 0.08603799 0.81405526]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [22]:
N = np.random.random((10,10))
Nmin, Nmax = N.min(), N.max()
print(Nmin, Nmax)

0.01266402103229114 0.9980105154329503


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)



In [5]:
Y = np.random.random(30)
m = Y.mean()
print(m)

0.577417424619838


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [6]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [7]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```



In [10]:
#Uma vez que NaN é um tipo em si, é usado para atribuir variáveis cujos valores ainda não foram calculados. 
#Método 1 : Para verificar se há NaN, podemos usar a função math. isnan() , pois NaN não pode ser testado usando o operador ==.

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [11]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [14]:
M = np.zeros((8,8),dtype=int)
M[1::2,::2] = 1
M[::2,1::2] = 1
print(M)

# Solução alternativa: usando remodelação
arr = np.ones(64,dtype=int)
arr[::2]=0
arr = arr.reshape((8,8))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [15]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [16]:
X = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(X)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [17]:
L = np.random.random((5,5))
L = (Z - np.mean (L)) / (np.std (L))
print(L)

[[-1.78708843 -1.78708843 -1.78708843 -1.78708843 -1.78708843]
 [ 1.80363759 -1.78708843 -1.78708843 -1.78708843 -1.78708843]
 [-1.78708843  5.39436361 -1.78708843 -1.78708843 -1.78708843]
 [-1.78708843 -1.78708843  8.98508963 -1.78708843 -1.78708843]
 [-1.78708843 -1.78708843 -1.78708843 12.57581565 -1.78708843]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [19]:
color = np.dtype([("r", np.ubyte, (1,)), ("g", np.ubyte, (1,)), ("b", np.ubyte, (1,)), ("a", np.ubyte, (1,))])
print(color)

[('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [21]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)



In [22]:
D = np.arange(11)
D[(3 < D) & (D <= 8)] *= -1
print(D)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [23]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [26]:
Z = np.ones(3)
Z**Z
#2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z

array([1., 1., 1.])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [30]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_380/548293649.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
/tmp/ipykernel_380/548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [32]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[ 5.  4.  8.  2.  4. -4. -3.  6. -6.  2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [33]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1, Z2)
print(np.intersect1d(Z1,Z2))

[5 7 5 9 0 5 4 3 1 7] [7 2 0 8 3 2 6 4 2 9]
[0 3 4 7 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)



In [6]:
# Suicide mode on
defaults = np.seterr(all ="ignore")
Z = np.ones(1)/0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3)/0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [2]:
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_368/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [3]:
yesterday = np.datetime64('today') - np.timedelta64(1)
print(yesterday)
today     = np.datetime64('today')
print(today)
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(tomorrow)

2022-11-02
2022-11-03
2022-11-04


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [4]:
J = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(J)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [5]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [7]:
X = np.random.uniform(0,10,3)
print(X)
print(X - X%1)
print(X // 1)
print(np.floor(X))
print(X.astype(int))
print(np.trunc(X))

[1.05084227 7.31646041 5.47300611]
[1. 7. 5.]
[1. 7. 5.]
[1. 7. 5.]
[1 7 5]
[1. 7. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [8]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [9]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [10]:
Y = np.linspace(0,1,11,endpoint=False)[1:]
print(Y)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [11]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.04671359 0.13837093 0.17788575 0.39594936 0.49051321 0.66095443
 0.82036694 0.84630617 0.90830473 0.93448311]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [12]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [13]:
A = np.random.randint(0,2,3)
B = np.random.randint(0,2,3)
print(A, B)

#Assumindo a forma idêntica das matrizes e uma tolerância para a comparação de valores
equal = np.allclose(A,B)
print(equal)

#Verificando os valores da forma e do elemento, sem tolerância (os valores devem ser exatamente iguais)
equal = np.array_equal(A,B)
print(equal)

[1 0 0] [0 0 0]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [14]:
Z = np.zeros(10)
Z.flags.writeable = False
try:
    Z[0] = 1
except Exception as e:
    print(e)

assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [15]:
C = np.random.random((10,2))
X,Y = C[:,0], C[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.94483308 1.00336208 0.80191487 0.07225563 0.33741384 0.99489835
 1.27985282 0.72289545 0.77542207 0.34019189]
[0.93744825 1.19882108 0.5155672  0.24407598 0.1746401  0.45281194
 0.80482502 0.9059544  0.13978145 1.05732257]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [16]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.61385446 0.61013514 0.3996144  0.48479358 0.25155529 0.33580158
 0.62156146 0.         0.23526612 0.3370851 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [17]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [18]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [0]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

#### 49. How to print all the values of an array? (★★☆)

In [4]:
np.set_printoptions(threshold=float("inf"))
Z = np.random.random((4,4))
print(Z)

[[0.27388359 0.64690848 0.88717418 0.00695521]
 [0.67029388 0.76418022 0.34205772 0.96064903]
 [0.35577124 0.63408725 0.90668137 0.86228975]
 [0.01221817 0.18518037 0.54133541 0.93103321]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [5]:
T = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(T-v)).argmin()
print(T[index])

40


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [6]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/tmp/ipykernel_378/274409719.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [7]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

#Muito mais rápido com scipy
import scipy

import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.69520774 0.42965298 0.78111567 0.64873062 0.44007548
  0.41577139 0.4534842  0.83119819 0.6180316 ]
 [0.69520774 0.         0.32636281 0.28886345 0.05133989 0.36714243
  0.36831718 0.44213743 0.1825362  0.2245135 ]
 [0.42965298 0.32636281 0.         0.54083666 0.27508198 0.05874818
  0.32907752 0.43193934 0.50186611 0.18884909]
 [0.78111567 0.28886345 0.54083666 0.         0.31795987 0.59535074
  0.36774372 0.3715306  0.18087989 0.50333431]
 [0.64873062 0.05133989 0.27508198 0.31795987 0.         0.31662473
  0.34039768 0.4220775  0.23082882 0.18589242]
 [0.44007548 0.36714243 0.05874818 0.59535074 0.31662473 0.
  0.38517614 0.48752749 0.54659876 0.19627125]
 [0.41577139 0.36831718 0.32907752 0.36774372 0.34039768 0.38517614
  0.         0.10325504 0.4487631  0.43243843]
 [0.4534842  0.44213743 0.43193934 0.3715306  0.4220775  0.48752749
  0.10325504 0.         0.48905649 0.53139089]
 [0.83119819 0.1825362  0.50186611 0.18087989 0.23082882 0.54659876
  0.4487631  0.48905

[[0.         0.51807097 0.46289584 0.52777901 0.2853372  0.44429471
  0.26924964 0.32176126 0.34118375 0.23225412]
 [0.51807097 0.         0.7075764  0.08939372 0.67553524 0.45288369
  0.25409311 0.28690358 0.77024    0.70765745]
 [0.46289584 0.7075764  0.         0.77043439 0.7337318  0.28571148
  0.57470909 0.42433309 0.76066558 0.34360711]
 [0.52777901 0.08939372 0.77043439 0.         0.64757651 0.52882835
  0.25881373 0.3461048  0.74499069 0.73450952]
 [0.2853372  0.67553524 0.7337318  0.64757651 0.         0.72490681
  0.43478727 0.57207612 0.09882338 0.42767006]
 [0.44429471 0.45288369 0.28571148 0.52882835 0.72490681 0.
  0.40350537 0.20868238 0.78539906 0.47314779]
 [0.26924964 0.25409311 0.57470909 0.25881373 0.43478727 0.40350537
  0.         0.19683396 0.52517322 0.47941152]
 [0.32176126 0.28690358 0.42433309 0.3461048  0.57207612 0.20868238
  0.19683396 0.         0.64826336 0.45174139]
 [0.34118375 0.77024    0.76066558 0.74499069 0.09882338 0.78539906
  0.52517322 0.64826

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [8]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [9]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")

Z = np.genfromtxt(s, delimiter=",", dtype=np.int)

print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/tmp/ipykernel_378/3012329279.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [10]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [11]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [12]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [15]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.38162925  0.04218516 -0.09720366  0.00304528  0.03450192 -0.03239535
  -0.02854466 -0.41314339 -0.06070561  0.17063107]
 [-0.18347349  0.50714654 -0.39777035  0.05447376 -0.29443801  0.42546517
   0.44762512 -0.37943621 -0.38284066  0.20324812]
 [-0.21644989  0.46305921  0.20083431  0.05102555 -0.30934919  0.25455662
   0.24901801 -0.35151585 -0.25986768 -0.08131108]
 [ 0.08973576 -0.34401804  0.00295494 -0.2057136  -0.00549761  0.21491916
   0.26812923 -0.06328655  0.15618368 -0.11340696]
 [-0.12775397  0.17917909  0.0583752   0.092898   -0.07590754 -0.10726706
  -0.38169701  0.33213117  0.20051435 -0.17047223]]


#### 59. How to sort an array by the nth column? (★★☆)

In [16]:
C = np.random.randint(0,10,(3,3))
print(C)
print(C[C[:,1].argsort()])

[[6 4 5]
 [0 5 1]
 [2 7 0]]
[[6 4 5]
 [0 5 1]
 [2 7 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [17]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [18]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.489984850607455


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [19]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [20]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [21]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

np.add.at(Z, I, 1)
print(Z)

[1. 2. 5. 4. 1. 5. 1. 2. 5. 4.]
[1. 3. 9. 7. 1. 9. 1. 3. 9. 7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [22]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [24]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)

#Observe que devemos calcular 256*256 primeiro. 
#Caso contrário, o numpy apenas promoverá F.dtype para 'uint16' e ocorrerá overfolw

F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)


8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [25]:
A = np.random.randint(0,10,(3,4,3,4))
# solução passando uma tupla de eixos (introduzido no numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
#solução achatando as duas últimas dimensões em uma 
#(útil para funções que não aceitam tuplas para argumento de eixo)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[63 54 68 45]
 [46 39 65 57]
 [60 68 38 70]]
[[63 54 68 45]
 [46 39 65 57]
 [60 68 38 70]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [26]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

#Solução Pandas como referência devido ao código mais intuitivo

import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.61202599 0.4368537  0.55318888 0.53546772 0.42704153 0.59238334
 0.53810565 0.58544963 0.50653883 0.39006826]


0    0.612026
1    0.436854
2    0.553189
3    0.535468
4    0.427042
5    0.592383
6    0.538106
7    0.585450
8    0.506539
9    0.390068
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [27]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Versão lenta
np.diag(np.dot(A, B))

#Versão rápida
np.sum(A * B.T, axis=1)

# Versão mais rápida
np.einsum("ij,ji->i", A, B)

array([0.82933311, 2.42314032, 1.03916215, 0.94694601, 0.21685156])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [28]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [29]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [30]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [33]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 3, 74) ( 3, 87) ( 4, 25) ( 4, 39) ( 5, 23) ( 5, 37) ( 5, 45) ( 5, 62)
 ( 9, 15) ( 9, 73) (15, 73) (21, 36) (21, 50) (23, 45) (25, 39) (26, 80)
 (26, 84) (36, 50) (37, 62) (41, 43) (41, 44) (43, 44) (43, 46) (43, 87)
 (44, 85) (44, 93) (46, 87) (74, 87) (80, 84) (85, 93)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [34]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [35]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [36]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [37]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.14878416, -0.2509204 ,  0.83528334, -0.96764893, -0.18861422,
       -0.24737805, -0.8479587 , -0.14019505, -0.71910983,  0.53131091,
        0.5282228 , -0.37573694,  0.18641644,  0.70015955, -0.02862806,
       -0.99216578, -0.33379662, -0.19539628, -0.54918157, -0.97406865,
        0.69345787, -0.79661438, -0.63590092, -0.51349939, -0.59212218,
        0.08863001, -0.35236834, -0.18595749, -0.34085089, -0.52730573,
       -0.29719472,  0.93793638,  0.23532454, -0.96822299,  0.93155929,
       -0.00135076, -0.32673373, -0.93455125, -0.55387442,  0.07251742,
        0.12377257,  0.40882997, -0.77077838, -0.60277008,  0.56914686,
       -0.09894151, -0.97900766, -0.57121337,  0.00287518,  0.98607922,
       -0.17917604, -0.90814015, -0.41545529, -0.58574968,  0.25777972,
        0.9907788 , -0.3749196 ,  0.41991934,  0.28864122,  0.25648041,
       -0.82159819, -0.75760675, -0.51592921,  0.21611286, -0.33533944,
       -0.29199435, -0.31648326, -0.56013719,  0.44598256, -0.09

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [38]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 5.15979185  5.47036417  6.39050242 10.25725492  6.01425894  4.3749931
  6.15267703  8.4165527   7.00763448  3.36124491]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [39]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[12.64495306  9.01115507  0.94427279  2.39454113 11.14466999  6.11167587
   4.62740469  9.57557216  6.29772841  4.28685271]
 [ 4.90102268  5.49772799  6.23867778  9.83746428 10.5517545   4.20730454
   7.31017312  0.92175608  1.87166219  5.25369334]
 [ 0.72784428  3.09330538  2.01726816  1.75299055  1.03685364  5.74216457
  16.23989447  3.64705173 11.29362474  0.73576671]
 [ 2.73066598  1.88117037  2.37661922  6.04064017  6.42552989  4.49864901
  11.10478776  0.75316831  6.14110899  2.29337951]
 [11.85274434  8.70370466  0.09342664  3.27213326 11.16221929  5.00467796
   4.84176433  8.67546151  5.73612672  3.19958235]
 [13.20358491 10.20281387  0.63195138  3.95473024 12.59912041  5.92896582
   3.34920389  9.93232388  4.65283996  2.96660963]
 [ 9.26087848  2.57944712  8.73561622  5.29738421  3.51824572  6.4407014
  11.46048945  7.19001055 14.61426719 10.59958975]
 [ 0.10633573  1.4823737   0.37290751  4.12615266  3.08405591  6.22720999
  14.48816579  3.33145151  8.86663115  1.34350601]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [40]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[2 2 2 3 5 9 3 0 7 8]
 [5 1 5 3 9 9 5 9 2 7]
 [2 6 0 5 8 0 7 2 9 4]
 [4 8 0 1 9 2 9 0 5 0]
 [3 8 5 5 5 1 2 1 0 2]
 [6 1 9 1 1 9 6 9 0 5]
 [3 2 1 0 1 5 6 5 7 1]
 [2 5 7 4 3 8 5 6 1 7]
 [8 2 7 7 0 0 4 2 2 6]
 [7 5 1 1 9 2 9 1 4 3]]
[[0 0 0 0 0]
 [0 2 2 2 3]
 [0 5 1 5 3]
 [0 2 6 0 5]
 [0 4 8 0 1]]


/tmp/ipykernel_378/1159162857.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [41]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [42]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [43]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [44]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 1 2]
   [3 2 4]
   [1 1 0]]

  [[1 2 3]
   [2 4 2]
   [1 0 1]]

  [[2 3 3]
   [4 2 0]
   [0 1 1]]

  [[3 3 3]
   [2 0 0]
   [1 1 4]]

  [[3 3 0]
   [0 0 0]
   [1 4 3]]

  [[3 0 2]
   [0 0 2]
   [4 3 2]]

  [[0 2 3]
   [0 2 3]
   [3 2 0]]

  [[2 3 0]
   [2 3 0]
   [2 0 0]]]


 [[[3 2 4]
   [1 1 0]
   [2 4 0]]

  [[2 4 2]
   [1 0 1]
   [4 0 1]]

  [[4 2 0]
   [0 1 1]
   [0 1 0]]

  [[2 0 0]
   [1 1 4]
   [1 0 4]]

  [[0 0 0]
   [1 4 3]
   [0 4 3]]

  [[0 0 2]
   [4 3 2]
   [4 3 0]]

  [[0 2 3]
   [3 2 0]
   [3 0 1]]

  [[2 3 0]
   [2 0 0]
   [0 1 4]]]


 [[[1 1 0]
   [2 4 0]
   [3 4 0]]

  [[1 0 1]
   [4 0 1]
   [4 0 0]]

  [[0 1 1]
   [0 1 0]
   [0 0 4]]

  [[1 1 4]
   [1 0 4]
   [0 4 3]]

  [[1 4 3]
   [0 4 3]
   [4 3 4]]

  [[4 3 2]
   [4 3 0]
   [3 4 0]]

  [[3 2 0]
   [3 0 1]
   [4 0 3]]

  [[2 0 0]
   [0 1 4]
   [0 3 3]]]


 [[[2 4 0]
   [3 4 0]
   [4 3 0]]

  [[4 0 1]
   [4 0 0]
   [3 0 4]]

  [[0 1 0]
   [0 0 4]
   [0 4 1]]

  [[1 0 4]
   [0 4 3]
   [4 1 1]]

  [[0 4 3]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [46]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 8  1 16  6  8]
 [ 1  4  9  9  9]
 [16  9  9 42 11]
 [ 6  9 42  2  9]
 [ 8  9 11  9  0]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [47]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [48]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [49]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 1
  1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1
  1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [50]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

#Lento
print (Z[np.argsort(Z)[-n:]])

#Rápido
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9997 9999 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [52]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [53]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [55]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.4 s ± 17.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


424 ms ± 27.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


386 ms ± 44.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [56]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 3 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)



In [57]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 3 1]
 [1 4 1]
 [0 2 4]
 [0 1 2]
 [2 3 2]
 [0 2 4]
 [1 1 2]
 [4 3 4]
 [0 0 0]
 [4 4 3]]
[[4 3 1]
 [1 4 1]
 [0 2 4]
 [0 1 2]
 [2 3 2]
 [0 2 4]
 [1 1 2]
 [4 3 4]
 [4 4 3]]
[[4 3 1]
 [1 4 1]
 [0 2 4]
 [0 1 2]
 [2 3 2]
 [0 2 4]
 [1 1 2]
 [4 3 4]
 [4 4 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [58]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [59]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [1 0 1]
 [1 1 0]]
[[0 0 0]
 [0 0 1]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [60]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.20507798, 0.31786069, 0.21928919, 0.0255818 , 0.29870324,
        0.16258186, 0.13713199, 0.17219083, 0.12254057, 0.30515058],
       [0.3241796 , 0.50246228, 0.34664414, 0.04043875, 0.47217891,
        0.25700332, 0.21677312, 0.27219283, 0.19370755, 0.48237062],
       [0.13579588, 0.21047687, 0.14520607, 0.01693942, 0.19779144,
        0.10765635, 0.09080429, 0.11401909, 0.08114233, 0.20206066],
       [0.03698455, 0.05732422, 0.03954745, 0.00461352, 0.05386929,
        0.02932064, 0.02473091, 0.03105356, 0.02209944, 0.05503203],
       [0.54284684, 0.84138564, 0.58046428, 0.0677157 , 0.79067537,
        0.43035848, 0.36299201, 0.45579369, 0.32436813, 0.80774166],
       [0.4174044 , 0.6469561 , 0.44632911, 0.05206778, 0.60796409,
        0.33091014, 0.27911089, 0.35046772, 0.24941231, 0.62108665],
       [0.59039687, 0.91508582, 0.63130936, 0.07364718, 0.85993365,
        0.46805522, 0.39478787, 0.4957184 , 0.35278077, 0.87849484],
       [0.23172673, 0.35916493, 0.2477846

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [64]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [65]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [66]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.16626369  0.18084428]
